export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST';
export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS';
export const ACCOUNT_LIST_FAIL = 'ACCOUNT_LIST_FAIL';

export const ACCOUNT_EDIT_REQUEST = 'ACCOUNT_EDIT_REQUEST';
export const ACCOUNT_EDIT_SUCCESS = 'ACCOUNT_EDIT_SUCCESS';
export const ACCOUNT_EDIT_FAIL = 'ACCOUNT_EDIT_FAIL';

export const ACCOUNT_GET_REQUEST = 'ACCOUNT_GET_REQUEST';
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS';
export const ACCOUNT_GET_FAIL = 'ACCOUNT_GET_FAIL';