export const CHAT_ADD_REQUEST = 'CHAT_ADD_REQUEST';
export const CHAT_ADD_SUCCESS = 'CHAT_ADD_SUCCESS';
export const CHAT_ADD_FAIL = 'CHAT_ADD_FAIL';

export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST';
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL';