export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const BOOSTER_ADD_REQUEST = 'BOOSTER_ADD_REQUEST';
export const BOOSTER_ADD_SUCCESS = 'BOOSTER_ADD_SUCCESS';
export const BOOSTER_ADD_FAIL = 'BOOSTER_ADD_FAIL';

export const BOOSTER_EDIT_REQUEST = 'BOOSTER_EDIT_REQUEST';
export const BOOSTER_EDIT_SUCCESS = 'BOOSTER_EDIT_SUCCESS';
export const BOOSTER_EDIT_FAIL = 'BOOSTER_EDIT_FAIL';

export const BOOSTER_DELETE_REQUEST = 'BOOSTER_DELETE_REQUEST';
export const BOOSTER_DELETE_SUCCESS = 'BOOSTER_DELETE_SUCCESS';
export const BOOSTER_DELETE_FAIL = 'BOOSTER_DELETE_FAIL';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAIL = 'USER_EDIT_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNIN_SIGNOUT';